---
apiVersion: v1
kind: Service
metadata:
  name: sample-service
  namespace: sample-app
  labels:
    app: sample-app
spec:
  type: ClusterIP
  selector:
    app: sample-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
