apiVersion: v1
kind: Service
metadata:
  name: task-manager-service
  namespace: kubernetes-cluster
  labels:
    app: task-manager
spec:
  selector:
    app: task-manager
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30080  # Optional: specify a port (30000-32767)
  type: NodePort
